---
- hosts: all
  tasks:
  - name: status {{ mytype }}
    command: java -{{ mytype }}
    register: st
    #ignore_errors: true
    failed_when: st.rc != 1 and st.rc != 0 and st.rc != 3 
  
  - debug:
      var: st

  - name: next
    command: echo "hello"
    when: st.msg == "[Errno 2] No such file or directory"
    
